name: to_do_list
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  get:
  flutter:
    sdk: flutter
  page_transition: "^2.1.0"
  image_picker: ^1.1.2
  video_player: ^2.2.19
  mime: ^1.0.0
  local_auth: ^2.2.0
  sqflite: ^2.3.2
  flutter_loader: ^0.2.6
  loading_animation_widget:
  cupertino_icons: ^1.0.6
  syncfusion_flutter_sliders: ^25.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  syncfusion_flutter_sliders: ^25.2.7
  connectivity_plus: ^2.3.4
  table_calendar: ^3.0.9
  url_launcher: ^6.2.6


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  assets:
    - images/intro.png
    - images/list.png
    - images/login.png
    - images/google.png
    - images/null.png


