// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDg3Glmo8LSAPFyPagGw-AsvGuxI2Okbo',
    appId: '1:527919222124:web:28651f91eb60cddc063749',
    messagingSenderId: '527919222124',
    projectId: 'goalgetterapp-1c56c',
    authDomain: 'goalgetterapp-1c56c.firebaseapp.com',
    storageBucket: 'goalgetterapp-1c56c.appspot.com',
    measurementId: 'G-YCH57PX70S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkm9wynbKkuTjDqNGeXkdsiq6cy3_ff6o',
    appId: '1:527919222124:android:2586c7e347cf3a5d063749',
    messagingSenderId: '527919222124',
    projectId: 'goalgetterapp-1c56c',
    storageBucket: 'goalgetterapp-1c56c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKnhO8HV5bl5uURBnRL-zxGj-hjJ-5rCo',
    appId: '1:527919222124:ios:58c6e0d9a00c7cb4063749',
    messagingSenderId: '527919222124',
    projectId: 'goalgetterapp-1c56c',
    storageBucket: 'goalgetterapp-1c56c.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDg3Glmo8LSAPFyPagGw-AsvGuxI2Okbo',
    appId: '1:527919222124:web:a19f711f6e05fd2b063749',
    messagingSenderId: '527919222124',
    projectId: 'goalgetterapp-1c56c',
    authDomain: 'goalgetterapp-1c56c.firebaseapp.com',
    storageBucket: 'goalgetterapp-1c56c.appspot.com',
    measurementId: 'G-BLE3MNDPT1',
  );
}
